triggers:
- envs: []
  last_enabled_at: null
  name: get_lacity_active_businesses_data
  pipeline_uuid: lacity_active_businesses
  schedule_interval: '@monthly'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-15 07:00:00
  status: inactive
  variables: {}
